### ISSUE TITLE
shorter solution for StepsGenerator

### ISSUE THREAD

**Issue by nkiesel** [igorwojda/kotlin-coding-puzzle#1]
Tried to run that in intellj w/o Android but failed to make that happen.

Anyway, looked at one problem and found a (IMHO more elegant) and def. more compact solution

```kotlin
private fun generateSteps(n: Int) = List(n) { i -> "#".repeat(i + 1) + " ".repeat(n - i - 1) }
```

**Comment by igorwojda** [comment]
1. Nice solution, concise, and elegant - really like it. 
I have added it to repo with small change - removal of explicit lambda parameter because its type can be inferred and it does not really overlap with anything
`private fun generateSteps(n: Int) = List(n) { "#".repeat(it + 1) + " ".repeat(n - it - 1) }`

2. Here is the video that shows how to run the project. Please take look and let me know how if it works for you.
https://1drv.ms/v/s!AkZ_52b5bWyOgrIsPbGB2qV27nwVEQ

3. I have added you to contributors list :-)

**Comment by igorwojda** [comment]
Since there is no answer to this. I am closing this issue.
Please reopen it if you still have a problem with running the tests.
